version: "3.3"
services:
  upbit:
    build:
      context: "./"
    ports:
      - "1928:1928"
    networks:
      - network
    restart: always
    container_name: upbit_server
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    networks:
      - upbit
    restart: always
    ports:
      - "6381:6381"
    container_name: upbit_redis

  mongo:
    image: mongo
    restart: always
    container_name: upbit_mongo
    networks:
      - upbit
    ports:
      - "27006:27017"
    expose:
      - "27017"

networks:
  upbit:
